#Database
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#Logging
logging.level.root=INFO
logging.level.org.soundtrack=DEBUG

#Server
server.port=8080

#JWTSECRET
jwt.secret =
jwt.expiration =