#Spring configuration
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#Logging configuration
logging.level.root=INFO
logging.level.org.soundtrack=DEBUG
logging.pattern.console=%d{HH:mm:ss} [%level] %logger - %msg%n